MESSAGE_TYPE_LOGIN = 1
MESSAGE_TYPE_HANDSHAKE = 2
MESSAGE_TYPE_SYNC = 4
MESSAGE_TYPE_PIPE = 7
MESSAGE_TYPE_PIPE_SYNC = 8
MESSAGE_TYPE_PROBE = 10
MESSAGE_TYPE_PING = 13
MESSAGE_TYPE_DISCONNECT = 14

PROTOCOL_VERSION = 3

PIPE_PACKET_REQUEST = 0xf8
PIPE_PACKET_RESPONSE = 0xf9
PIPE_PACKET_ANNOUNCE = 0xfa

SET_POWER_STATE = 0xd0
SET_BRIGHTNESS = 0xd2
SET_COLOR = 0xe2
DEVICE_STATUS = 0xdb
COMBO_CONTROL = 0xf0
QUERY_DEVICE_STATUS_PAGES = 0x52